# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Attribute\Model\Attribute:
    type: mappedSuperclass
    repositoryClass: Accard\Bundle\AttributeBundle\Doctrine\ORM\AttributeRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
