accard_api_patient:
    resource: @AccardApiBundle/Resources/config/routing/patient.yml
    prefix: /patients
    options:
        expose: true

fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml
