accard_api_patient_index:
    path: /
    methods: [GET]
    defaults:
        _controller: accard.controller.patient:indexAction
        _dag:
            method: createFilterPaginator
            arguments: [$criteria, $sorting]
            paginate: $limit
            sortable: true
            filterable: true
            sorting: { id: desc }
            serialization_groups: [Default]

accard_api_patient_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: accard.controller.patient:showAction
        _dag:
            serialization_groups: [api]
