# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Phase\Model\Phase:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        label:
            type: string
            nullable: false
        presentation:
            type: string
            nullable: false
        order:
            column: orderNumber
            type: integer
            nullable: false
