# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Field\Model\Field:
    type: mappedSuperclass
    repositoryClass: Accard\Bundle\FieldBundle\Doctrine\ORM\FieldRepository 

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 120
            nullable: false
            unique: true
        presentation:
            type: string
            length: 120
            nullable: false
        type:
            type: string
            length: 36
            nullable: false
        allowMultiple:
            type: boolean
            nullable: false
        configuration:
            type: array

    manyToOne:
        option:
            targetEntity: Accard\Component\Option\Model\OptionInterface
            cascade: ["persist"]
            joinColumn:
                name: optionId
