# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.grid.factory.class: Accard\Component\Widget\Grid\GridFactory
    accard.grid.builder.class: Accard\Component\Widget\Grid\GridBuilder
    accard.row.builder_factory.class: Accard\Component\Widget\Grid\RowBuilderFactory
    accard.column.builder_factory.class: Accard\Component\Widget\Grid\ColumnBuilderFactory
    accard.column.builder.class: Accard\Component\Widget\Grid\ColumnBuilder
    accard.grid.provider.class: Accard\Component\Widget\Grid\GridProvider

services:

    accard.row.builder_factory:
        class: %accard.row.builder_factory.class%
        arguments: ["@accard.widget.factory"]

    accard.column.builder_factory:
        class: %accard.column.builder_factory.class%
        arguments: ["@accard.widget.factory"]

    accard.grid.factory:
        class: %accard.grid.factory.class%
        arguments: ["@accard.row.builder_factory", "@accard.column.builder_factory", "@accard.widget.factory"]

    accard.grid.builder:
        class: %accard.grid.builder.class%

    accard.column.builder:
        class: %accard.column.builder.class%

    accard.grid.provider:
        class: %accard.grid.provider.class%
        arguments: ["@accard.repository.canvas", "@accard.grid.factory"]


