# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
     accard.controller.canvas.class: Accard\Bundle\CanvasBundle\Controller\CanvasController

services:
     accard.controller.canvas:
          class: %accard.controller.canvas.class%
          arguments: ["@templating"]

