accard_frontend_activity_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.activity:showAction
        _dag:
            template: Theme:Frontend/Activity:show.html.twig
    options:
        expose: true

accard_frontend_activity_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.activity:createAction
        _dag:
            template: Theme:Frontend/Activity:create.html.twig
            redirect:
                route: accard_frontend_activity_update
                parameters: { patient: $patient, id: resource.id }
    options:
        expose: true

accard_frontend_activity_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.activity:updateAction
        _dag:
            template: Theme:Frontend/Activity:update.html.twig
            redirect:
                route: accard_frontend_activity_update
                parameters: { patient: $patient, id: $id }
    options:
        expose: true

accard_frontend_activity_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.activity:deleteAction
        _dag:
            redirect:
                route: accard_frontend_deleted
                parameters: { type: 'activity', id: $id }
