accard_frontend_attribute_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.attribute:showAction
        _accard:
            template: Theme:Frontend/Attribute:show.html.twig
    options:
        expose: true

accard_frontend_attribute_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.attribute:createAction
        _accard:
            template: Theme:Frontend/Attribute:create.html.twig
            redirect:
                route: accard_frontend_attribute_update
                parameters: { patient: $patient, id: resource.id }
    options:
        expose: true

accard_frontend_attribute_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.attribute:updateAction
        _accard:
            template: Theme:Frontend/Attribute:update.html.twig
            redirect:
                route: accard_frontend_attribute_update
                parameters: { patient: $patient, id: $id }
    options:
        expose: true

accard_frontend_attribute_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.attribute:deleteAction
        _accard:
            redirect:
                route: accard_frontend_deleted
                parameters: { type: 'attribute', id: $id }
