accard_frontend_regimen_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.regimen:showAction
        _dag:
            template: Theme:Frontend/Regimen:show.html.twig
    options:
        expose: true

accard_frontend_regimen_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.regimen:createAction
        _dag:
            template: Theme:Frontend/Regimen:create.html.twig
            redirect:
                route: accard_frontend_regimen_update
                parameters: { patient: $patient, id: resource.id }
    options:
        expose: true

accard_frontend_regimen_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.regimen:updateAction
        _dag:
            template: Theme:Frontend/Regimen:update.html.twig
            redirect:
                route: accard_frontend_regimen_update
                parameters: { patient: $patient, id: $id }
    options:
        expose: true

accard_frontend_regimen_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.regimen:deleteAction
        _dag:
            redirect:
                route: accard_frontend_deleted
                parameters: { type: 'regimen', id: $id }
