accard_frontend_sample_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample:showAction
        _accard:
            template: Theme:Frontend/Sample:show.html.twig
    options:
        expose: true

accard_frontend_sample_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.sample:createAction
        _accard:
            template: Theme:Frontend/Sample:create.html.twig
            redirect:
                route: accard_frontend_sample_update
                parameters: { patient: $patient, id: resource.id }
    options:
        expose: true

accard_frontend_sample_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample:updateAction
        _accard:
            template: Theme:Frontend/Sample:update.html.twig
            redirect:
                route: accard_frontend_sample_update
                parameters: { patient: $patient, id: $id }
    options:
        expose: true

accard_frontend_sample_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample:deleteAction
        _accard:
            redirect:
                route: accard_frontend_deleted
                parameters: { type: 'sample', id: $id }
