# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Drug\Model\DrugGroup:
    type: mappedSuperclass
    table: accard_drug_group

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            nullable: false
            unique: true
        presentation:
            type: string
            nullable: false

    manyToMany:
        drugs:
            targetEntity: Accard\Component\Drug\Model\DrugInterface
            inversedBy: groups
            joinTable:
                name: accard_drugs_groups
                joinColumns:
                    groupId: ~
                inverseJoinColumns:
                    drugId: ~