# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source drug.

Accard\Component\Drug\Model\Drug:
    type: mappedSuperclass
    table: accard_drug

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            nullable: false
            unique: true
        presentation:
            type: string
            nullable: false

    oneToMany:
        brands:
            targetEntity: Accard\Component\Drug\Model\DrugInterface
            mappedBy: generic

    manyToOne:
        generic:
            targetEntity: Accard\Component\Drug\Model\DrugInterface
            inversedBy: brands
            joinColumn:
                name: genericId

    manyToMany:
        groups:
            targetEntity: Accard\Component\Drug\Model\DrugGroupInterface
            mappedBy: drugs
