parameters:

    penn_user_provider.class: Accard\Bundle\UserBundle\Security\User\PennUserProvider
    accard.user.remote_user.listener.class: Accard\Bundle\UserBundle\EventListener\RemoteUserInjectionListener

services:

    # Penn personnel directory service
    penn_directory_cache:
        class: DAG\Penn\Directory\Cache\APCCache
        arguments: []

    penn_directory_client:
        class: DAG\Penn\Directory\Personnel\Client
        arguments: ["@penn_directory_cache"]

    # PennGroups lookup service
    penngroups_ldap_client:
        class: DAG\Penn\Groups\LDAP\Client
        arguments: ["%penngroups_ldap_host%", "%penngroups_kerberos_principal%", "%penngroups_password%", "@penn_directory_cache"]

    penngroups_webservice_client:
        class: DAG\Penn\Groups\WS\Client
        arguments: ["%penngroups_ws_url%", "%penngroups_kerberos_principal%", "%penngroups_password%"]

    penngroups_client:
        class: DAG\Penn\Groups\Client
        arguments: ["@penngroups_ldap_client", "@penngroups_webservice_client"]

    # User provider implementation
    penn_user_provider:
        class: "%penn_user_provider.class%"
        arguments:  ["@penn_directory_client", "@penngroups_client"]

    # Cosign authentication hook
    cosign_authenticator:
        class:  Accard\Bundle\UserBundle\Security\CoSignAuthenticator

    accard.user.remote_user.listener:
        class: %accard.user.remote_user.listener.class%
        arguments:
            - @kernel
            - @service_container
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }
