# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Regimen\Model\Prototype:
    type: mappedSuperclass
    table: accard_regimen_prototype

    fields:
        allowDrug:
            type: boolean
            nullable: true

    manyToOne:
        drugGroup:
            targetEntity: Accard\Component\Drug\Model\DrugGroupInterface
            joinColumn:
                name: drugGroupId
                nullable: true
