# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Regimen\Model\Regimen:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    oneToMany:
        fields:
            targetEntity: Accard\Component\Regimen\Model\FieldValueInterface
            mappedBy: subject
            orphanRemoval: true
            cascade: ["all"]