# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Behavior\Model\Behavior:
    type: mappedSuperclass
    repositoryClass: Accard\Bundle\BehaviorBundle\Doctrine\ORM\BehaviorRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        startDate:
            type: datetime
            nullable: false
        endDate:
            type: datetime
            nullable: true

    oneToMany:
        fields:
            targetEntity: Accard\Component\Behavior\Model\FieldValueInterface
            mappedBy: subject
            cascade: ["persist", "remove"]
            orphanRemoval: true
