parameters:

    accard.repository.template.class: Accard\Bundle\TemplateBundle\Doctrine\ORM\TemplateRepository
    accard.controller.template.class: Accard\Bundle\TemplateBundle\Controller\TemplateController
    accard.form.template.class: Accard\Bundle\TemplateBundle\Form\Type\TemplateType
    accard.model.template.class: Accard\Bundle\TemplateBundle\Entity\Template

services:

    accard.repository.template:
        class: %accard.repository.template.class%
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Accard\Bundle\TemplateBundle\Entity\Template

    accard.twig_database_loader:
        class: Accard\Bridge\Twig\Loader\TwigDatabaseLoader
        arguments: [@accard.repository.template]

    accard.twig_filesystem_loader:
        class: Accard\Bridge\Twig\Loader\TwigAccardFilesystemLoader
        arguments:
            - "AccardWebBundle"
            - @templating.locator
            - @templating.name_parser

    accard.twig_chain_loader:
        class: Twig_Loader_Chain
        calls:
            - [ addLoader, [@accard.twig_database_loader] ]
            - [ addLoader, [@accard.twig_filesystem_loader] ]
            - [ addLoader, [@twig.loader] ]

    accard.controller.template:
        class: %accard.controller.template.class%
        arguments: [@accard.repository.template]
        calls:
            - ['setContainer', ["@service_container"]]

    accard.form.type.accard_template:
        class: %accard.form.template.class%
        calls: 
            - [ setBundles, ['%kernel.bundles%']]
        tags: [{ name: form.type, alias: accard_template }]