# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_api_patient:
    type: rest
    resource: @AccardWebBundle/Resources/config/routing/api/patient.yml
    prefix: /patient