# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_outcomes_main:
    path: /
    defaults:
        _controller: AccardOutcomesBundle:Outcomes:main

accard_outcomes_state:
    path: /state.json
    defaults:
        _controller: AccardWebBundle:Frontend:state