# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.outcomes.manager.class: Accard\Bundle\OutcomesBundle\Outcomes\Manager
    accard.outcomes.filter_registry.class: Accard\Bundle\OutcomesBundle\Outcomes\FilterRegistry

services:

    accard.outcomes.manager:
        class: %accard.outcomes.manager.class%
        arguments:
            - @accard.outcomes.filter_registry
        calls:
            - [ "setContainer", ["@service_container"]]
            - [ "setState", ["@=service('accard.state').getState()"]]

    accard.outcomes.filter_registry:
        class: %accard.outcomes.filter_registry.class%
