# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Bundle\CanvasBundle\Entity\Canvas:
     type: entity
     table: accard_canvas
     repositoryClass: Accard\Bundle\CanvasBundle\Doctrine\ORM\CanvasRepository

     id:
         id:
            type: integer
            generator:
                strategy: AUTO

     fields:
           route:
                type: string
           grid:
                type: json_array