# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.behavior.class: Accard\Bundle\BehaviorBundle\Form\Type\BehaviorType
    accard.builder.behavior.class: Accard\Component\Behavior\Builder\BehaviorBuilder

services:

    accard.form.type.behavior:
        class: %accard.form.type.behavior.class%
        arguments:
            - %accard.model.behavior.class%
            - %accard.validation_group.behavior%
            - @accard.builder.behavior
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_behavior }

    accard.form.type.alcohol_behavior:
        class: %accard.form.type.alcohol_behavior.class%
        arguments:
            - %accard.model.alcohol_behavior.class%
            - %accard.validation_group.behavior%
            - @accard.builder.behavior
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_alcohol_behavior }

    accard.form.type.smoking_behavior:
        class: %accard.form.type.smoking_behavior.class%
        arguments:
            - %accard.model.smoking_behavior.class%
            - %accard.validation_group.behavior%
            - @accard.builder.behavior
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_smoking_behavior }

    accard.form.type.illicit_drug_behavior:
        class: %accard.form.type.illicit_drug_behavior.class%
        arguments:
            - %accard.model.illicit_drug_behavior.class%
            - %accard.validation_group.behavior%
            - @accard.builder.behavior
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_illicit_drug_behavior }

    accard.form.type.occupation_behavior:
        class: %accard.form.type.occupation_behavior.class%
        arguments:
            - %accard.model.occupation_behavior.class%
            - %accard.validation_group.behavior%
            - @accard.builder.behavior
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_occupation_behavior }

    accard.form.type.education_behavior:
        class: %accard.form.type.education_behavior.class%
        arguments:
            - %accard.model.education_behavior.class%
            - %accard.validation_group.behavior%
            - @accard.builder.behavior
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_education_behavior }

    accard.builder.behavior:
        class: %accard.builder.behavior.class%
        arguments:
            - @accard.manager.behavior
            - @accard.repository.behavior
