# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.behavior.class: Accard\Bundle\BehaviorBundle\Form\Type\BehaviorType
    accard.builder.behavior.class: Accard\Component\Behavior\Builder\BehaviorBuilder

services:

    accard.form.type.behavior:
        class: %accard.form.type.behavior.class%
        arguments:
            - %accard.model.behavior.class%
            - %accard.validation_group.behavior%
            - @accard.builder.behavior
        tags:
            - { name: form.type, alias: accard_behavior }

    accard.builder.behavior:
        class: %accard.builder.behavior.class%
        arguments:
            - @accard.manager.behavior
            - @accard.repository.behavior
            - @accard.repository.behavior_field
            - @accard.repository.behavior_field_value