# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.attribute.class: Accard\Bundle\AttributeBundle\Form\Type\AttributeType
    accard.builder.attribute.class: Accard\Component\Attribute\Builder\AttributeBuilder

services:

    accard.form.type.attribute:
        class: %accard.form.type.attribute.class%
        arguments:
            - %accard.model.attribute.class%
            - %accard.validation_group.attribute%
            - @accard.builder.attribute
        tags:
            - { name: form.type, alias: accard_attribute }

    accard.builder.attribute:
        class: %accard.builder.attribute.class%
        arguments:
            - @accard.manager.attribute
            - @accard.repository.attribute
            - @accard.repository.attribute_field
            - @accard.repository.attribute_field_value
