# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_activity_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.activity:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_activity_index_by_prototype:
    pattern: /{prototype}/
    methods: [GET]
    defaults:
        _controller: accard.controller.activity:indexByPrototypeAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:indexByPrototype.html.twig
            sortable: true
            criteria:
                prototype: $prototype
            paginate: 25

accard_frontend_activity_show:
    pattern: /{prototype}/{id}
    methods: [GET]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.activity:showAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:show.html.twig

accard_frontend_activity_create:
    pattern: /{prototype}/new
    methods: [GET, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+" }
    defaults:
        _controller: accard.controller.activity:createAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:create.html.twig
            redirect:
                route: accard_frontend_activity_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_activity_update:
    pattern: /{prototype}/{id}/edit
    methods: [GET, PUT, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.activity:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:update.html.twig
            redirect:
                route: accard_frontend_activity_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_activity_delete:
    pattern: /{prototype}/{id}
    methods: [DELETE]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.activity:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:delete.html.twig
            redirect:
                route: accard_frontend_activity_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }
