# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_activity_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.activity:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_activity_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.activity:showAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:show.html.twig

accard_frontend_activity_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.activity:createAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:create.html.twig
            redirect: accard_frontend_activity_show

accard_frontend_activity_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.activity:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:update.html.twig
            redirect: accard_frontend_activity_show

accard_frontend_activity_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.activity:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Activity:delete.html.twig
            redirect: accard_frontend_activity_index
