# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_attribute_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.attribute:indexAction
        _dag:
            template: Theme:Frontend/Attribute:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_attribute_index_by_prototype:
    pattern: /{prototype}/
    methods: [GET]
    defaults:
        _controller: accard.controller.attribute:indexByPrototypeAction
        _dag:
            template: Theme:Frontend/Attribute:indexByPrototype.html.twig
            sortable: true
            criteria:
                prototype: $prototype
            paginate: 25

accard_frontend_attribute_show:
    pattern: /{prototype}/{id}
    methods: [GET]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.attribute:showAction
        _dag:
            template: Theme:Frontend/Attribute:show.html.twig

accard_frontend_attribute_create:
    pattern: /{prototype}/new
    methods: [GET, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+" }
    defaults:
        _controller: accard.controller.attribute:createAction
        _dag:
            template: Theme:Frontend/Attribute:create.html.twig
            redirect:
                route: accard_frontend_attribute_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_attribute_update:
    pattern: /{prototype}/{id}/edit
    methods: [GET, PUT, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.attribute:updateAction
        _dag:
            template: Theme:Frontend/Attribute:update.html.twig
            redirect:
                route: accard_frontend_attribute_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_attribute_delete:
    pattern: /{prototype}/{id}
    methods: [DELETE]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.attribute:deleteAction
        _dag:
            template: Theme:Frontend/Attribute:delete.html.twig
            redirect:
                route: accard_frontend_attribute_index_by_prototype
                parameters: { prototype: resource.prototype.name }

