# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_behavior_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.behavior:indexAction
        _dag:
            template: Theme:Frontend/Behavior:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_behavior_index_by_prototype:
    pattern: /{prototype}/
    methods: [GET]
    defaults:
        _controller: accard.controller.behavior:indexByPrototypeAction
        _dag:
            template: Theme:Frontend/Behavior:indexByPrototype.html.twig
            sortable: true
            criteria:
                prototype: $prototype
            paginate: 25

accard_frontend_behavior_show:
    pattern: /{prototype}/{id}
    methods: [GET]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.behavior:showAction
        _dag:
            template: Theme:Frontend/Behavior:show.html.twig

accard_frontend_behavior_create:
    pattern: /{prototype}/new
    methods: [GET, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+" }
    defaults:
        _controller: accard.controller.behavior:createAction
        _dag:
            template: Theme:Frontend/Behavior:create.html.twig
            redirect:
                route: accard_frontend_behavior_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_behavior_update:
    pattern: /{prototype}/{id}/edit
    methods: [GET, PUT, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.behavior:updateAction
        _dag:
            template: Theme:Frontend/Behavior:update.html.twig
            redirect:
                route: accard_frontend_behavior_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_behavior_delete:
    pattern: /{prototype}/{id}
    methods: [DELETE]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.behavior:deleteAction
        _dag:
            template: Theme:Frontend/Behavior:delete.html.twig
            redirect:
                route: accard_frontend_behavior_index_by_prototype
                parameters: { prototype: resource.prototype.name }

