# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_import_accept:
    pattern: /accept/{subject}/{id}
    methods: [GET]
    requirements:
        subject: '[a-z_-]{3,36}'
        id: \d+
    defaults:
        _controller: accard.controller.import:acceptAction

accard_frontend_import_decline:
    pattern: /decline/{subject}/{id}
    methods: [GET]
    requirements:
        subject: '[a-z_-]{3,36}'
        id: \d+
    defaults:
        _controller: accard.controller.import:declineAction
