# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_homepage:
    path: /
    defaults:
        _controller: AccardWebBundle:Frontend:main

accard_frontend_patient:
    resource: @AccardWebBundle/Resources/config/routing/frontend/patient.yml
    prefix: /patient

accard_frontend_diagnosis:
    resource: @AccardWebBundle/Resources/config/routing/frontend/diagnosis.yml
    prefix: /diagnosis

accard_frontend_regimen:
    resource: @AccardWebBundle/Resources/config/routing/frontend/regimen.yml
    prefix: /activity/regimen

accard_frontend_activity:
    resource: @AccardWebBundle/Resources/config/routing/frontend/activity.yml
    prefix: /activity

accard_frontend_sample:
    resource: @AccardWebBundle/Resources/config/routing/frontend/sample.yml
    prefix: /sample

accard_frontend_behavior:
    resource: @AccardWebBundle/Resources/config/routing/frontend/behavior.yml
    prefix: /behavior

accard_frontend_attribute:
    resource: @AccardWebBundle/Resources/config/routing/frontend/attribute.yml
    prefix: /attribute

accard_frontend_import:
    resource: @AccardWebBundle/Resources/config/routing/frontend/import.yml
    prefix: /import

accard_frontend_flow:
    resource: @AccardFlowBundle/Resources/config/routing.yml
    prefix: /flow

accard_frontend_search:
    resource: @AccardWebBundle/Resources/config/routing/frontend/search.yml
    prefix: /search

accard_frontend_pds:
    resource: @AccardPDSBundle/Resources/config/routing.yml
    prefix: /pds

accard_frontend_cpd:
    resource: @AccardCPDBundle/Resources/config/routing.yml
    prefix: /cpd

accard_frontend_option_quickadd:
    path: /option/add/{option}
    defaults:
        _controller: AccardWebBundle:Frontend:quickAddOption
        _requirements: { option: \d+ }

accard_frontend_prototype_form:
    path: /prototype/form/{type}
    defaults:
        _controller: AccardWebBundle:Frontend:prototypeChoiceForm
        _requirements: { type: activity|attribute|behavior|regimen|sample }

accard_frontend_prototype_redirect:
    path: /prototype/redirect/{type}
    defaults:
        _controller: AccardWebBundle:Frontend:prototypeRedirect
        _requirements: { type: activity|attribute|behavior|regimen|sample }

accard_frontend_prototype_list:
    path: /prototype/form/activity/{type}
    defaults:
        _controller: AccardWebBundle:Frontend:prototypeList

accard_frontend_last_created:
    path: /resource/last-created
    defaults:
        _controller: AccardWebBundle:Frontend:lastCreated
