# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_patient_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.patient:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Patient:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_patient_import:
    pattern: /import
    methods: [GET]
    defaults:
        _controller: accard.controller.patient:importAction
        _accard:
            template: AccardWebBundle:Frontend/Patient:import.html.twig
            sortable: true
            paginate: 25

accard_frontend_patient_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.patient:showAction
        _accard:
            template: AccardWebBundle:Frontend/Patient:show.html.twig

accard_frontend_patient_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.patient:createAction
        _accard:
            template: AccardWebBundle:Frontend/Patient:create.html.twig
            redirect: accard_frontend_patient_show

accard_frontend_patient_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.patient:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Patient:update.html.twig
            redirect: accard_frontend_patient_show

accard_frontend_patient_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.patient:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Patient:delete.html.twig
            redirect: accard_frontend_patient_index
