# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_sample_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.sample:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_sample_source_collection_index:
    pattern: /collection
    methods: [GET]
    defaults:
        _controller: accard.controller.sample_source:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:sourceIndex.html.twig
            sortable: true
            method: createCollectionPaginator
            paginate: 25

accard_frontend_sample_source_derivation_index:
    pattern: /derivation
    methods: [GET]
    defaults:
        _controller: accard.controller.sample_source:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:sourceIndex.html.twig
            sortable: true
            method: createDerivationPaginator
            paginate: 25

accard_frontend_sample_index_by_prototype:
    pattern: /{prototype}/
    methods: [GET]
    defaults:
        _controller: accard.controller.sample:indexByPrototypeAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:indexByPrototype.html.twig
            sortable: true
            criteria:
                prototype: $prototype
            paginate: 25

accard_frontend_sample_source_collection_show:
    pattern: /collection/{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample_source:showAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:showSource.html.twig

accard_frontend_sample_source_derivation_show:
    pattern: /derivation/{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample_source:showAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:showSource.html.twig

accard_frontend_sample_show:
    pattern: /{prototype}/{id}
    methods: [GET]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.sample:showAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:show.html.twig

accard_frontend_sample_source_collection_create:
    pattern: /collection/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.sample_source:createAction
        _accard:
            form: accard_sample_source_collection
            template: AccardWebBundle:Frontend/Sample:sourceCreate.html.twig
            redirect: accard_frontend_sample_source_collection_index

accard_frontend_sample_source_derivation_create:
    pattern: /derivation/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.sample_source:createAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:sourceCreate.html.twig
            redirect: accard_frontend_sample_source_derivation_index
            form: accard_sample_source_derivation

accard_frontend_sample_create:
    pattern: /{prototype}/new
    methods: [GET, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+" }
    defaults:
        _controller: accard.controller.sample:createAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:create.html.twig
            redirect:
                route: accard_frontend_sample_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_sample_source_collection_update:
    pattern: /collection/{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample_source:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:sourceUpdate.html.twig
            redirect: accard_frontend_sample_source_collection_index
            form: accard_sample_source_collection

accard_frontend_sample_source_derivation_update:
    pattern: /derivation/{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample_source:updateActiion
        _accard:
            template: AccardWebBundle:Frontend/Sample:sourceUpdate.html.twig
            redirect: accard_frontend_sample_source_derivation_index
            form: accard_sample_source_derivation

accard_frontend_sample_update:
    pattern: /{prototype}/{id}/edit
    methods: [GET, PUT, POST]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.sample:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:update.html.twig
            redirect:
                route: accard_frontend_sample_index_by_prototype
                parameters: { prototype: resource.prototype.name, id: resource.id }

accard_frontend_sample_source_collection_delete:
    pattern: /collection/{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample_source:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:delete.html.twig
            redirect:
                route: accard_frontend_sample_source_collection_index
                parameters: { id: resource.id }

accard_frontend_sample_source_derivation_delete:
    pattern: /derivation/{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.sample_source:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:delete.html.twig
            redirect:
                route: accard_frontend_sample_source_derivation_index
                parameters: { id: resource.id }

accard_frontend_sample_delete:
    pattern: /{prototype}/{id}
    methods: [DELETE]
    requirements: { prototype: "[a-zA-Z1-9\-_\/]+", id: \d+ }
    defaults:
        _controller: accard.controller.sample:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Sample:delete.html.twig
            redirect:
                route: accard_frontend_sample_index
                parameters: { prototype: resource.prototype.name, id: resource.id }
