# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_activity_design:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.activity:designAction
        _accard:
            template: AccardWebBundle:Backend/Activity:design.html.twig

accard_backend_activity_prototype:
    pattern: /prototype/{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.activity_prototype:showAction
        _accard:
            template: AccardWebBundle:Backend/Activity:showPrototype.html.twig

accard_backend_activity_prototype_create:
    pattern: /prototype/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.activity_prototype:createAction
        _accard:
            template: AccardWebBundle:Backend/Activity:prototypeCreate.html.twig
            redirect: accard_backend_activity_design

accard_backend_activity_prototype_update:
    pattern: /prototype/{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: accard.controller.activity_prototype:updateAction
        _accard:
            template: AccardWebBundle:Backend/Activity:prototypeUpdate.html.twig
            redirect: accard_backend_activity_design