# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_behavior_design:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.behavior:designAction
        _dag:
            template: AccardWebBundle:Backend/Behavior:design.html.twig

accard_backend_behavior_settings_update:
    pattern: /settings/update
    methods: [PUT, POST]
    defaults:
        namespace: behavior
        _controller: dag.controller.settings:updateAction
        _dag:
            redirect:
                route: accard_backend_behavior_design
                parameters: { type: settings, action: update }

accard_backend_behavior_prototype_create:
    pattern: /prototype/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.behavior_prototype:createAction
        _dag:
            template: AccardWebBundle:Backend/Behavior:prototypeCreate.html.twig
            redirect:
                route: accard_backend_behavior_design
                parameters: { type: prototype, action: create, id: resource.id }

accard_backend_behavior_prototype_update:
    pattern: /prototype/{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: accard.controller.behavior_prototype:updateAction
        _dag:
            template: AccardWebBundle:Backend/Behavior:prototypeUpdate.html.twig
            redirect:
                route: accard_backend_behavior_design
                parameters: { type: prototype, action: update, id: resource.id }

accard_backend_behavior_prototype_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.behavior_prototype:deleteAction
        _dag:
            redirect:
                route: accard_backend_behavior_design
                parameters: { type: prototype, action: delete }

accard_backend_behavior_field_create:
    pattern: /field/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.behavior_prototype_field:createAction
        _dag:
            template: AccardWebBundle:Backend/Behavior:fieldCreate.html.twig
            redirect:
                route: accard_backend_behavior_design
                parameters: { type: field, action: create, id: resource.id }

accard_backend_behavior_field_update:
    pattern: /field/{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: accard.controller.behavior_prototype_field:updateAction
        _dag:
            template: AccardWebBundle:Backend/Behavior:fieldUpdate.html.twig
            redirect:
                route: accard_backend_behavior_design
                parameters: { type: field, action: update, id: resource.id }

accard_backend_behavior_field_delete:
    pattern: /field/{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.behavior_prototype_field:deleteAction
        _dag:
            redirect:
                route: accard_backend_behavior_design
                parameters: { type: field, action: delete }
