# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_canvas_design:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.canvas:designAction

accard_backend_canvas_grid:
    pattern: /view/grid
    methods: [GET]
    defaults:
         _controller: accard.controller.canvas:gridAction

accard_backend_canvas_grid_config:
    pattern: /view/grid
    methods: [POST]
    defaults:
         _controller: accard.controller.canvas:configAction

accard_backend_canvas_widget:
    pattern: /view/widget
    methods: [GET, POST]
    defaults:
         _controller: accard.controller.canvas:widgetAction