# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_option_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.option:indexAction
        _accard:
            template: AccardWebBundle:Backend/Option:index.html.twig

accard_backend_option_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.option:createAction
        _accard:
            template: AccardWebBundle:Backend/Option:create.html.twig
            redirect: accard_backend_option_index

accard_backend_option_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.option:updateAction
        _accard:
            template: AccardWebBundle:Backend/Option:update.html.twig
            redirect: accard_backend_option_index

accard_backend_option_update_redirect:
    pattern: /{name}/edit
    methods: [GET]
    requirements: { id: '[a-z_-]{3,36}' }
    defaults:
        _controller: accard.controller.option:redirectNameAction
        _accard:
            redirect: accard_backend_option_update

