# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_patient_design:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.patient:designAction
        _accard:
            template: Theme:Backend/Patient:design.html.twig

accard_backend_patient_settings_update:
    pattern: /settings/update
    methods: [PUT, POST]
    defaults:
        _controller: accard.controller.settings:updateAction
        namespace: patient
        redirect: accard_backend_patient_design

accard_backend_patient_field_create:
    pattern: /field/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.patient_field:createAction
        _accard:
            template: Theme:Backend/Patient:fieldCreate.html.twig
            redirect: accard_backend_patient_design

accard_backend_patient_field_update:
    pattern: /field/{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: accard.controller.patient_field:updateAction
        _accard:
            template: Theme:Backend/Patient:fieldUpdate.html.twig
            redirect: accard_backend_patient_design

accard_backend_patient_field_delete:
    pattern: /field/{id}
    methods: [DELETE]
    defaults:
        _controller: accard.controller.patient_field:deleteAction
        _accard:
            template: Theme:Backend/Misc:delete.html.twig
            redirect: accard_backend_patient_design

accard_backend_patient_phase_index:
    pattern: /phase
    methods: [GET]
    defaults:
        _controller: accard.controller.patient_phase:indexAction
        _accard:
            template: Theme:Backend/PatientPhase:index.html.twig
            sortable: true
            paginate: 12
            sorting:
                order: asc

accard_backend_patient_phase_create:
    pattern: /phase/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.patient_phase:createAction
        _accard:
            template: AccardWebBundle:Backend/PatientPhase:create.html.twig
            redirect: accard_backend_patient_phase_index

accard_backend_patient_phase_update:
    pattern: /phase/{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.patient_phase:updateAction
        _accard:
            template: Theme:Backend/PatientPhase:update.html.twig
            redirect: accard_backend_patient_phase_index

accard_backend_patient_phase_delete:
    pattern: /phase/{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.patient_phase:deleteAction
        _accard:
            template: Theme:Backend/PatientPhase:delete.html.twig
            redirect: accard_backend_patient_phase_index
