# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_general_settings:
    pattern: /general
    defaults:
        _controller: dag.controller.settings:updateAction
        namespace: general
        template: AccardWebBundle:Backend/Settings:general.html.twig

accard_backend_theme_settings:
    pattern: /theme
    defaults:
        _controller: dag.controller.settings:updateAction
        namespace: theme
        template: AccardWebBundle:Backend/Settings:theme.html.twig
