
accard_backend_template_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.template:indexAction

accard_backend_template_design:
    pattern: /design/{name}/{version}
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.template:designAction
        version: null

accard_backend_template_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.template:createAction

accard_backend_template_history:
    pattern: /history/{name}
    methods: [GET]
    defaults:
        _controller: accard.controller.template:historyAction