# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_flow_start:
    path: /{scenarioAlias}
    methods: [GET]
    defaults:
        _controller: accard.flow.controller:startAction

accard_flow_display:
    path: /{scenarioAlias}/{stepName}
    methods: [GET]
    defaults:
        _controller: accard.flow.controller:displayAction

accard_flow_forward:
    path: /{scenarioAlias}/{stepName}
    methods: [POST]
    defaults:
        _controller: accard.flow.controller:forwardAction