# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type_extension.date_defaults.class: Accard\Bundle\WebBundle\Form\Extension\DateDefaultsExtension

services:

    accard.form.type_extension.date:
        class: %accard.form.type_extension.date_defaults.class%
        arguments: ['date']
        tags:
            - { name: form.type_extension, alias: date }

    accard.form.type_extension.datetime:
        class: %accard.form.type_extension.date_defaults.class%
        arguments: ['datetime']
        tags:
            - { name: form.type_extension, alias: datetime }

    accard.form.type_extension.birthday:
        class: %accard.form.type_extension.date_defaults.class%
        arguments: ['birthday']
        tags:
            - { name: form.type_extension, alias: birthday }