# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.provider.diagnosis.class: Accard\Bundle\DiagnosisBundle\Provider\DiagnosisProvider
    accard.provider.diagnosis_code.class: Accard\Bundle\DiagnosisBundle\Provider\CodeProvider
    accard.provider.diagnosis_code_group.class: Accard\Bundle\DiagnosisBundle\Provider\CodeGroupProvider

services:

    accard.provider.diagnosis:
        class: %accard.provider.diagnosis.class%
        arguments:
            - @accard.repository.diagnosis
            - @accard.provider.diagnosis_code
            - @accard.provider.diagnosis_code_group

    accard.provider.diagnosis_code:
        class: %accard.provider.diagnosis_code.class%
        arguments:
            - @accard.repository.diagnosis_code
            - @accard.provider.diagnosis_code_group

    accard.provider.diagnosis_code_group:
        class: %accard.provider.diagnosis_code_group.class%
        arguments:
            - @accard.repository.diagnosis_code_group
