# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Option\Model\Option:
    type: mappedSuperclass
    table: accard_option

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 120
            nullable: false
        presentation:
            type: string
            length: 120
            nullable: false

    oneToMany:
        values:
            targetEntity: Accard\Component\Option\Model\OptionValueInterface
            mappedBy: option
            orphanRemoval: true
            cascade: ["persist", "remove"]
