# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Activity\Model\Prototype:
    type: mappedSuperclass
    table: accard_activity_prototype

    fields:
        allowDrug:
            type: boolean
            nullable: false
