# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Dylan Pierce <piercedy@upenn.edu>

Accard\Component\Core\Model\Activity:
    type: entity
    table: accard_activity
    repositoryClass: Accard\Bundle\ActivityBundle\Doctrine\ORM\ActivityRepository

    manyToOne:
        patient:
            targetEntity: Accard\Component\Patient\Model\PatientInterface
            inversedBy: activities
            joinColumn:
                name: patientId
                referencedColumnName: id
                nullable: false
        diagnosis:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            inversedBy: activities
            joinColumn:
                name: diagnosisId
                referencedColumnName: id
                nullable: true
        regimen:
            targetEntity: Accard\Component\Regimen\Model\RegimenInterface
            inversedBy: activities
            joinColumn:
                name: regimenId
                referencedColumnName: id
                nullable: true