# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\AlcoholBehavior:
    type: mappedSuperclass
    table: accard_alcohol_behavior

    fields:
        frequency:
            type: integer
