# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\Behavior:
    type: entity
    table: accard_behavior
    repositoryClass: Accard\Bundle\BehaviorBundle\Doctrine\ORM\BehaviorRepository

    manyToOne:
        patient:
            targetEntity: Accard\Component\Patient\Model\PatientInterface
            inversedBy: behaviors
            joinColumn:
                name: patientId
                referencedColumnName: id
                nullable: false
