# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\Diagnosis:
    type: mappedSuperclass
    table: accard_diagnosis
    repositoryClass: Accard\Bundle\DiagnosisBundle\Doctrine\ORM\DiagnosisRepository

    manyToOne:
        patient:
            targetEntity: Accard\Component\Patient\Model\PatientInterface
            inversedBy: diagnoses
            joinColumn:
                name: patientId
                referencedColumnName: id
                nullable: false

    oneToMany:
        activities:
            targetEntity: Accard\Component\Activity\Model\ActivityInterface
            mappedBy: diagnosis
            orphanRemoval: true
            cascade: ["persist", "remove"]
        phases:
            targetEntity: Accard\Component\Core\Model\DiagnosisPhaseInstanceInterface
            mappedBy: target
            orphanRemoval: true
            cascade: ["persist", "remove"]
        regimens:
            targetEntity: Accard\Component\Regimen\Model\RegimenInterface
            mappedBy: diagnosis
            orphanRemoval: true
            cascade: ["persist"]