# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\EducationBehavior:
    type: mappedSuperclass
    table: accard_education_behavior

    fields:
        level:
            type: string
        years:
            type: integer
        completed:
            type: boolean
