# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\IllicitDrugBehavior:
    type: mappedSuperclass
    table: accard_illicit_drug_behavior

    fields:
        type:
            type: string
        frequency:
            type: string
        method:
            type: string

