# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\ImportActivity:
    type: mappedSuperclass
    table: accard_import_activity

    fields:
        descriptions:
            type: array
            nullable: false
        status:
            type: integer
            nullable: false

    manyToOne:
        patient:
            targetEntity: Accard\Component\Patient\Model\PatientInterface
            #inversedBy: activities
            joinColumn:
                name: patientId
                referencedColumnName: id
                nullable: false
        diagnosis:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            #inversedBy: diagnoses
            joinColumn:
                name: diagnosisId
                referencedColumnName: id
                nullable: true
