# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\Patient:
    type: mappedSuperclass
    table: accard_patient
    repositoryClass: Accard\Bundle\PatientBundle\Doctrine\ORM\PatientRepository

    oneToMany:
        diagnoses:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            mappedBy: patient
            orphanRemoval: true
            cascade: ["persist", "remove"]
        behaviors:
            targetEntity: Accard\Component\Behavior\Model\BehaviorInterface
            mappedBy: patient
            orphanRemoval: true
            cascades: ["persist", "remove"]
        activities:
            targetEntity: Accard\Component\Activity\Model\ActivityInterface
            mappedBy: patient
            orphanRemoval: true
            cascade: ["persist", "remove"]
            orderBy: {'activityDate' : 'ASC'}
        attributes:
            targetEntity: Accard\Component\Attribute\Model\AttributeInterface
            mappedBy: patient
            orphanRemoval: true
            cascade: ["persist", "remove"]
        phases:
            targetEntity: Accard\Component\Core\Model\PatientPhaseInstanceInterface
            mappedBy: target
            orphanRemoval: true
            cascade: ["persist", "remove"]
        regimens:
            targetEntity: Accard\Component\Regimen\Model\RegimenInterface
            mappedBy: patient
            orphanRemoval: true
            casecade: ["persist", "remove"]
        samples:
            targetEntity: Accard\Component\Sample\Model\SampleInterface
            mappedBy: patient
            orphanRemoval: true
            cascade: ["persist", "remove"]
