# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Dylan Pierce <piercedy@upenn.edu>

Accard\Component\Core\Model\Regimen:
    type: entity
    table: accard_regimen
    repositoryClass: Accard\Bundle\RegimenBundle\Doctrine\ORM\RegimenRepository

    manyToOne:
        patient:
            targetEntity: Accard\Component\Patient\Model\PatientInterface
            #inversedBy: regimens
            joinColumn:
                name: patientId
                referencedColumnName: id
                nullable: false
        diagnosis:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            inversedBy: regimens
            joinColumn:
                name: diagnosisId
                referencedColumnName: id
                nullable: true

    oneToMany:
        activities:
            targetEntity: Accard\Component\Activity\Model\ActivityInterface
            mappedBy: regimen
            cascade: ["persist"]
