# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\Source:
    type: mappedSuperclass
    table: accard_sample_source
    repositoryClass: Accard\Bundle\SampleBundle\Doctrine\ORM\SourceRepository

    manyToOne:
        patient:
            targetEntity: Accard\Component\Patient\Model\PatientInterface
#            inversedBy: diagnoses
            joinColumn:
                name: patientId
                referencedColumnName: id
