# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:

    accard_hmtb.controller.class: Accard\Bundle\HMTBBundle\Controller\HMTBController

services:

    accard.connection.hmtb:
        alias: doctrine.dbal.accard_connection

    accard_hmtb.controller:
        class: "%accard_hmtb.controller.class%"
        arguments: ["@doctrine.orm.accard_entity_manager"]
