# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard_pds.controller.class: Accard\Bundle\PDSBundle\Controller\PDSController

services:

    accard.connection.pds:
        alias: doctrine.dbal.accard_connection

    accard_pds.controller:
        class: "%accard_pds.controller.class%"
        arguments: ["@doctrine.orm.accard_entity_manager"]
