# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_behavior_education_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.education_behavior:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Education:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_behavior_education_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.education_behavior:showAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Education:show.html.twig

accard_frontend_behavior_education_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.education_behavior:createAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Education:create.html.twig
            redirect: accard_frontend_behavior_education_show

accard_frontend_behavior_education_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.education_behavior:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Education:update.html.twig
            redirect: accard_frontend_behavior_education_show

accard_frontend_behavior_education_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.education_behavior:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Education:delete.html.twig
            redirect: accard_frontend_behavior_education_index
