# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_behavior_illicit_drug_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.illicit_drug_behavior:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/IllicitDrug:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_behavior_illicit_drug_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.illicit_drug_behavior:showAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/IllicitDrug:show.html.twig

accard_frontend_behavior_illicit_drug_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.illicit_drug_behavior:createAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/IllicitDrug:create.html.twig
            redirect: accard_frontend_behavior_illicit_drug_show

accard_frontend_behavior_illicit_drug_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.illicit_drug_behavior:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/IllicitDrug:update.html.twig
            redirect: accard_frontend_behavior_illicit_drug_show

accard_frontend_behavior_illicit_drug_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.illicit_drug_behavior:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/IllicitDrug:delete.html.twig
            redirect: accard_frontend_behavior_illicit_drug_index
