# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_behavior_occupation_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.occupation_behavior:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Occupation:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_behavior_occupation_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.occupation_behavior:showAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Occupation:show.html.twig

accard_frontend_behavior_occupation_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.occupation_behavior:createAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Occupation:create.html.twig
            redirect: accard_frontend_behavior_occupation_show

accard_frontend_behavior_occupation_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.occupation_behavior:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Occupation:update.html.twig
            redirect: accard_frontend_behavior_occupation_show

accard_frontend_behavior_occupation_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.occupation_behavior:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Occupation:delete.html.twig
            redirect: accard_frontend_behavior_occupation_index
