# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_frontend_behavior_smoking_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.smoking_behavior:indexAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Smoking:index.html.twig
            sortable: true
            paginate: 25

accard_frontend_behavior_smoking_show:
    pattern: /{id}
    methods: [GET]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.smoking_behavior:showAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Smoking:show.html.twig

accard_frontend_behavior_smoking_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.smoking_behavior:createAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Smoking:create.html.twig
            redirect: accard_frontend_behavior_smoking_show

accard_frontend_behavior_smoking_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.smoking_behavior:updateAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Smoking:update.html.twig
            redirect: accard_frontend_behavior_smoking_show

accard_frontend_behavior_smoking_delete:
    pattern: /{id}
    methods: [DELETE]
    requirements: { id: \d+ }
    defaults:
        _controller: accard.controller.smoking_behavior:deleteAction
        _accard:
            template: AccardWebBundle:Frontend/Behavior/Smoking:delete.html.twig
            redirect: accard_frontend_behavior_smoking_index
