# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Patient\Model\Patient:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: "mrn", message: accard.patient.mrn.unique, groups: ['accard'] }
    properties:
        mrn:
            - Regex: { pattern: "/^[0-9]{9}$/", message: accard.patient.mrn.regex, groups: ['accard'] }
        firstName:
            - NotBlank: { message: accard.patient.first_name.not_blank, groups: ['accard'] }
            - Length: { min: 3, max: 36, minMessage: accard.patient.first_name.length.min, maxMessage: accard.patient.first_name.length.max, groups: ['accard'] }
        lastName:
            - NotBlank: { message: accard.patient.last_name.not_blank, groups: ['accard'] }
            - Length: { min: 3, max: 36, minMessage: accard.patient.last_name.length.min, maxMessage: accard.patient.last_name.length.max, groups: ['accard'] }
        dateOfBirth:
            - NotBlank: { message: accard.patient.date_of_birth.not_blank, groups: ['accard'] }
            - DateTime: { message: accard.patient.date_of_birth.date, groups: ['accard'] }
        dateOfDeath:
            - DateTime: { message: accard.patient.date_of_death.date, groups: ['accard'] }
        gender:
            - NotBlank: { message: accard.patient.gender.not_blank, groups: ['accard'] }
            - Type: { type: Accard\Component\Option\Model\OptionValueInterface, message: accard.patient.gender.type, groups: ['accard'] }
        race:
            - NotBlank: { message: accard.patient.race.not_blank, groups: ['accard'] }
            - Type: { type: Accard\Component\Option\Model\OptionValueInterface, message: accard.patient.race.type, groups: ['accard'] }
        fields:
            - Valid: ~
            - All:
                - Type: { type: Accard\Component\Field\Model\FieldValueInterface, message: accard.patient.fields.type, groups: ['accard'] }
    getters:
        dateOfDeathValid:
            - "True": { message: accard.patient.date_of_death.valid, groups: ['accard'] }

Accard\Component\Patient\Model\Field: ~
Accard\Component\Patient\Model\FieldValue: ~
