# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.builder.regimen.class: Accard\Component\Regimen\Builder\RegimenBuilder

services:

    accard.form.type.regimen:
        class: %accard.form.type.regimen.class%
        arguments:
            - %accard.model.regimen.class%
            - %accard.validation_group.regimen%
            - @accard.builder.regimen
        tags: [{ name: form.type, alias: accard_regimen }]

    accard.builder.regimen:
        class: %accard.builder.regimen.class%
        arguments:
            - @accard.manager.regimen
            - @accard.repository.regimen
            - @accard.repository.regimen_field
            - @accard.repository.regimen_field_value
