# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Regimen\Model\Regimen:
    properties:
        startDate:
            - NotBlank: { message: accard.regimen.start_date.not_blank, groups: ['accard']}
            - DateTime: { message: accard.regimen.start_date.datetime, groups: ['accard']}
        endDate:
            - DateTime: { message: accard.regimen.end_date.date_time, groups: ['accard']}
        fields:
            - Valid: ~

    getters: ~

Accard\Component\Regimen\Model\Prototype:
    properties:
        name:
            - Regex: { pattern: "/^[a-z0-9-]+$/", message: accard.regimen_prototype.name.regex, groups: ['accard']}
            - Length: { min: 3, max: 60, minMessage: accard.regimen_prototype.name.length.min, maxMessage: accard.regimen_prototype.name.length.max, groups: ['accard']}
        presentation:
            - Length: { min: 3, max: 120, minMessage: accard.regimen_prototype.presentation.length.min, maxMessage: accard.regimen_prototype.presentation.length.max, groups: ['accard']}
        subjects:
            - Valid: ~
        fields:
            - Valid: ~

Accard\Component\Regimen\Model\Field:
    properties: ~
    getters: ~

Accard\Component\Regimen\Model\FieldValue:
    properties: ~
    getters: ~

Accard\Component\Regimen\Model\Source:
    properties: ~
    getters: ~