# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Diagnosis\Model\FieldValue:
    type: mappedSuperclass
    table: accard_diagnosis_field_value
