# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.phase_persistence_listener.class: Accard\Bundle\CoreBundle\EventListener\PhasePersistenceSubscriber 

services:

    accard.phase_persistence_listener:
        class: %accard.phase_persistence_listener.class%
        tags: [{ name: kernel.event_subscriber }]
