# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    accard.flow.scenario.basic_patient.class: Accard\Bundle\CoreBundle\Flow\Scenario\BasicPatientScenario
    accard.flow.step.create_patient.class: Accard\Bundle\CoreBundle\Flow\Step\CreatePatientStep
    accard.flow.step.create_diagnosis_phases.class: Accard\Bundle\CoreBundle\Flow\Step\CreateDiagnosisPhasesStep
    accard.flow.step.create_diagnosis.class: Accard\Bundle\CoreBundle\Flow\Step\CreateDiagnosisStep
    accard.flow.step.create_pre_existing_conditions.class : Accard\Bundle\CoreBundle\Flow\Step\CreatePreExistingConditionsStep
    accard.flow.step.finalize_patient.class: Accard\Bundle\CoreBundle\Flow\Step\FinalizePatientStep
    accard.form.extension.accard_diagnosis.class: Accard\Bundle\CoreBundle\Form\Extension\DiagnosisTypeExtension
    accard.form.extension.accard_behavior.class: Accard\Bundle\CoreBundle\Form\Extension\BehaviorTypeExtension

services:
    
    accard.flow.step.create_diagnosis_phases:
        class: %accard.flow.step.create_diagnosis_phases.class%
        arguments:
            - %accard.model.patient.class%
            - %accard.model.diagnosis.class%
        tags:
            - { name: accard.flow.step, alias: create_diagnosis_phases }

    accard.flow.scenario.basic_patient:
        class: %accard.flow.scenario.basic_patient.class%
        arguments:
            - "@accard.manager.patient"
        tags:
            - { name: accard.flow.scenario, alias: basic_patient }

    accard.flow.step.create_patient:
        class: %accard.flow.step.create_patient.class%
        arguments:
            - @accard.repository.patient
            - %accard.model.patient.class%
        tags:
            - { name: accard.flow.step, alias: create_patient }

    accard.flow.step.create_diagnosis:
        class: %accard.flow.step.create_diagnosis.class%
        arguments:
            - @accard.repository.diagnosis
            - %accard.model.diagnosis.class%
        tags:
            - { name: accard.flow.step, alias: create_diagnosis }

    accard.flow.step.finalize_patient:
        class: %accard.flow.step.finalize_patient.class%
        arguments:
            - %accard.model.patient.class%
            - %accard.model.diagnosis.class%
        tags:
            - { name: accard.flow.step, alias: finalize_patient }

    accard.flow.step.create_pre_existing_conditions:
        class: %accard.flow.step.create_pre_existing_conditions.class%
        arguments:
            - @accard.repository.diagnosis
            - %accard.model.diagnosis.class%
            - %accard.model.patient.class%
            - @accard.form.type.diagnosis
        tags:
            - { name: accard.flow.step, alias: create_pre_existing_conditions }
