# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type_extension.date_defaults.class: Accard\Bundle\WebBundle\Form\Extension\DateDefaultsExtension
    accard.form.type.accard_patient_phase.class: Accard\Bundle\CoreBundle\Form\Type\PatientPhaseType
    accard.form.type.accard_patient_phase_choice.class: Accard\Bundle\CoreBundle\Form\Type\PatientPhaseChoiceType
    accard.form.type.accard_patient_phase_instance.class: Accard\Bundle\CoreBundle\Form\Type\PatientPhaseInstanceType
    accard.form.type.accard_diagnosis_phase.class: Accard\Bundle\CoreBundle\Form\Type\DiagnosisPhaseType
    accard.form.type.accard_diagnosis_phase_choice.class: Accard\Bundle\CoreBundle\Form\Type\DiagnosisPhaseChoiceType
    accard.form.type.accard_diagnosis_phase_instance.class: Accard\Bundle\CoreBundle\Form\Type\DiagnosisPhaseInstanceType
    accard.form.extension.accard_attribute.class: Accard\Bundle\CoreBundle\Form\Extension\AttributeTypeExtension
    accard.form.extension.accard_diagnosis.class: Accard\Bundle\CoreBundle\Form\Extension\DiagnosisTypeExtension
    accard.form.extension.accard_behavior.class: Accard\Bundle\CoreBundle\Form\Extension\BehaviorTypeExtension
    accard.form.extension.accard_activity.class: Accard\Bundle\CoreBundle\Form\Extension\ActivityTypeExtension
    accard.form.extension.accard_sample.class: Accard\Bundle\CoreBundle\Form\Extension\SampleTypeExtension
    accard.form.extension.accard_sample_source.class: Accard\Bundle\CoreBundle\Form\Extension\SampleSourceTypeExtension
    accard.form.extension.accard_regimen.class: Accard\Bundle\CoreBundle\Form\Extension\RegimenTypeExtension

    accard.form.type.patient_diagnoses.class: Accard\Bundle\CoreBundle\Form\Type\PatientDiagnosesType
    accard.form.type.patient_filter.class: Accard\Bundle\CoreBundle\Form\Type\Filter\PatientFilterType

services:

    accard.form.type_extension.date:
        class: %accard.form.type_extension.date_defaults.class%
        arguments: ['date']
        tags: [{ name: form.type_extension, alias: date }]

    accard.form.type_extension.datetime:
        class: %accard.form.type_extension.date_defaults.class%
        arguments: ['datetime']
        tags: [{ name: form.type_extension, alias: datetime }]

    accard.form.type_extension.birthday:
        class: %accard.form.type_extension.date_defaults.class%
        arguments: ['birthday']
        tags: [{ name: form.type_extension, alias: birthday }]


    accard.form.type.accard_patient_phase:
        class: %accard.form.type.accard_patient_phase.class%
        arguments:
            - %accard.model.patient_phase.class%
            - %accard.validation_group.patient_phase%
        tags: [{ name: form.type, alias: accard_patient_phase }]

    accard.form.type.accard_patient_phase_choice:
        class: %accard.form.type.accard_patient_phase_choice.class%
        arguments:
            - %accard.model.patient_phase.class%
        tags: [{ name: form.type, alias: accard_patient_phase_choice }]

    accard.form.type.accard_patient_phase_instance:
        class: %accard.form.type.accard_patient_phase_instance.class%
        arguments:
            - %accard.model.patient_phase_instance.class%
            - %accard.model.patient_phase.class%
            - %accard.model.patient.class%
            - %accard.validation_group.patient_phase_instance%
        tags: [{ name: form.type, alias: accard_patient_phase_instance }]

    accard.form.type.accard_diagnosis_phase:
        class: %accard.form.type.accard_diagnosis_phase.class%
        arguments:
            - %accard.model.diagnosis_phase.class%
            - %accard.validation_group.diagnosis_phase%
        tags: [{ name: form.type, alias: accard_diagnosis_phase }]

    accard.form.type.accard_diagnosis_phase_choice:
        class: %accard.form.type.accard_diagnosis_phase_choice.class%
        arguments:
            - %accard.model.diagnosis_phase.class%
        tags: [{ name: form.type, alias: accard_diagnosis_phase_choice }]

    accard.form.type.accard_diagnosis_phase_instance:
        class: %accard.form.type.accard_diagnosis_phase_instance.class%
        arguments:
            - %accard.model.diagnosis_phase_instance.class%
            - %accard.model.diagnosis_phase.class%
            - %accard.model.diagnosis.class%
            - %accard.validation_group.diagnosis_phase_instance%
        tags: [{ name: form.type, alias: accard_diagnosis_phase_instance }]

    accard.form.extension.accard_attribute:
        class: %accard.form.extension.accard_attribute.class%
        arguments:
            - %accard.model.patient.class%
        tags: [{ name: form.type_extension, alias: accard_attribute }]

    accard.form.extension.accard_behavior:
        class: %accard.form.extension.accard_behavior.class%
        arguments:
            - %accard.model.patient.class%
        tags: [{ name: form.type_extension, alias: accard_behavior }]

    accard.form.extension.accard_diagnosis:
        class: %accard.form.extension.accard_diagnosis.class%
        tags: [{ name: form.type_extension, alias: accard_diagnosis }]

    accard.form.extension.accard_activity:
        class: %accard.form.extension.accard_activity.class%
        arguments:
            - %accard.model.patient.class%
            - @accard.repository.diagnosis
        tags: [{ name: form.type_extension, alias: accard_activity }]

    accard.form.extension.accard_sample:
        class: %accard.form.extension.accard_sample.class%
        arguments:
            - %accard.model.patient.class%
        tags: [{ name: form.type_extension, alias: accard_sample }]

    accard.form.extension.accard_sample_source:
        class: %accard.form.extension.accard_sample_source.class%
        arguments:
            - %accard.model.patient.class%
        tags: [{ name: form.type_extension, alias: accard_sample_source }]

    accard.form.extension.accard_regimen:
        class: %accard.form.extension.accard_regimen.class%
        arguments:
            - @accard.repository.patient
            - @accard.repository.diagnosis
            - @accard.repository.activity
        tags: [{ name: form.type_extension, alias: accard_regimen }]

    accard.form.type.patient_diagnoses:
        class: %accard.form.type.patient_diagnoses.class%
        arguments:
            - %accard.model.patient.class%
            - @accard.form.type.diagnosis
        tags: [{ name: form.type, alias: accard_patient_diagnoses }]

    accard.form.type.patient_filter:
        class: %accard.form.type.patient_filter.class%
        tags: [{ name: form.type, alias: accard_patient_filter }]
