# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.extension.accard_attribute.class: Accard\Bundle\CoreBundle\Form\Extension\AttributeTypeExtension
    accard.provider.import_patient.class: Accard\Bundle\CoreBundle\Provider\ImportPatientProvider

services:

    accard.provider.import_patient:
        class: %accard.provider.import_patient.class%
        arguments:
            - @accard.repository.import_patient

