# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.state.class: Accard\Bundle\CoreBundle\AccardState
    accard.state.registry.class: Accard\Bundle\CoreBundle\State\DecoratorRegistry
    accard.form.extension.accard_attribute.class: Accard\Bundle\CoreBundle\Form\Extension\AttributeTypeExtension
    accard.provider.import_patient.class: Accard\Bundle\CoreBundle\Provider\ImportPatientProvider
    accard.provider.import_activity.class: Accard\Bundle\CoreBundle\Provider\ImportActivityProvider
    accard.provider.import_sample.class: Accard\Bundle\CoreBundle\Provider\ImportSampleProvider
    accard.fixture.manager.class: Accard\Bundle\CoreBundle\DataFixtures\FixtureManager
    accard.fixture.option_builder.class: Accard\Bundle\CoreBundle\DataFixtures\OptionBuilder
    accard.fixture.option_value_builder.class: Accard\Bundle\CoreBundle\DataFixtures\OptionValueBuilder
    accard.json.transformer.listener: Accard\Bundle\CoreBundle\EventListener\JsonRequestTransformerListener
    doctrine.oracle.session_listener.class: Accard\Bundle\ResourceBundle\EventListener\OracleSessionInit

services:

    accard.state:
        class: %accard.state.class%
        arguments: ['@accard.state.registry']
        calls:
            - [setContainer, ["@service_container"]]

    accard.state.registry:
        class: %accard.state.registry.class%

    accard.provider.import_patient:
        class: %accard.provider.import_patient.class%
        arguments:
            - @accard.repository.import_patient

    accard.provider.import_activity:
        class: %accard.provider.import_activity.class%
        argument:
            - @accard.repository.import_activity

    accard.provider.import_sample:
        class: %accard.provider.import_sample.class%
        argument:
            - @accard.repository.import_sample

    accard.fixture.manager:
        class: %accard.fixture.manager.class%

    accard.fixture.option_builder:
        class: %accard.fixture.option_builder.class%
        calls:
            - [setOptionClass, ["%accard.model.option.class%"]]

    accard.fixture.option_value_builder:
        class: %accard.fixture.option_value_builder.class%
        calls:
            - [setOptionValueClass, ["%accard.model.optionvalue.class"]]

    doctrine.oracle.default_session_listener:
        class: %doctrine.oracle.session_listener.class%
        tags: [{ name: doctrine.event_listener, event: postConnect }]

    doctrine.oracle.accard_session_listener:
        class: %doctrine.oracle.session_listener.class%
        tags: [{ name: doctrine.event_listener, event: postConnect, connection: accard }]

#    kernel.event_listener.json_request_transformer:
#        class: %accard.json.transformer.listener%
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }