# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.state.class: Accard\Bundle\CoreBundle\AccardState
    accard.state.registry.class: Accard\Bundle\CoreBundle\State\DecoratorRegistry
    accard.form.extension.accard_attribute.class: Accard\Bundle\CoreBundle\Form\Extension\AttributeTypeExtension
    doctrine.oracle.session_listener.class: DAG\Bundle\ResourceBundle\EventListener\OracleSessionInit
    doctrine.extension.listener.class: Accard\Bundle\CoreBundle\EventListener\DoctrineExtensionListener

services:

    accard.state:
        class: %accard.state.class%
        arguments: ['@accard.state.registry']
        calls:
            - [setContainer, ["@service_container"]]

    accard.state.registry:
        class: %accard.state.registry.class%

    doctrine.oracle.default_session_listener:
        class: %doctrine.oracle.session_listener.class%
        tags: [{ name: doctrine.event_listener, event: postConnect }]

    doctrine.oracle.accard_session_listener:
        class: %doctrine.oracle.session_listener.class%
        tags: [{ name: doctrine.event_listener, event: postConnect, connection: accard }]

    doctrine.extension.listener:
        class: %doctrine.extension.listener.class%
        calls:
             - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    gedmo.listener.loggable:
          class: Gedmo\Loggable\LoggableListener
          tags:
              - { name: doctrine.event_subscriber, connection: default }
          calls:
              - [ setAnnotationReader, [ @annotation_reader ] ]