# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.settings_schema.general.class: Accard\Bundle\CoreBundle\Settings\GeneralSettingsSchema
    accard.settings_schema.theme.class: Accard\Bundle\CoreBundle\Settings\ThemeSettingsSchema
    accard.settings_schema.patient.class: Accard\Bundle\CoreBundle\Settings\PatientSettingsSchema
    accard.settings_schema.diagnosis.class: Accard\Bundle\CoreBundle\Settings\DiagnosisSettingsSchema
    accard.settings_schema.behavior.class: Accard\Bundle\CoreBundle\Settings\BehaviorSettingsSchema
    accard.settings_schema.attribute.class: Accard\Bundle\CoreBundle\Settings\AttributeSettingsSchema

services:

    accard.settings_schema.general:
        class: %accard.settings_schema.general.class%
        tags:
            - { name: accard.settings_schema, namespace: general }

    accard.settings_schema.theme:
        class: %accard.settings_schema.theme.class%
        tags:
            - { name: accard.settings_schema, namespace: theme }

    accard.settings_schema.patient:
        class: %accard.settings_schema.patient.class%
        tags:
            - { name: accard.settings_schema, namespace: patient }

    accard.settings_schema.diagnosis:
        class: %accard.settings_schema.diagnosis.class%
        tags:
            - { name: accard.settings_schema, namespace: diagnosis }

    accard.settings_schema.behavior:
        class: %accard.settings_schema.behavior.class%
        tags:
            - { name: accard.settings_schema, namespace: behavior }

    accard.settings_schema.attribute:
        class: %accard.settings_schema.attribute.class%
        tags:
            - { name: accard.settings_schema, namespace: attribute }