# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.activity_choice.class: Accard\Bundle\ActivityBundle\Form\Type\ActivityChoiceType
    accard.builder.activity.class: Accard\Component\Activity\Builder\ActivityBuilder
    accard.provider.activity.class: Accard\Component\Activity\Provider\ActivityProvider

services:

    accard.form.type.activity:
        class: %accard.form.type.activity.class%
        arguments:
            - %accard.model.activity.class%
            - %accard.validation_group.activity%
            - @accard.builder.activity
        tags: [{ name: form.type, alias: accard_activity }]

    accard.form.type.activity_choice:
        class: %accard.form.type.activity_choice.class%
        arguments:
            - @accard.repository.activity
        tags: [{ name: form.type, alias: accard_activity_choice }]

    accard.builder.activity:
        class: %accard.builder.activity.class%
        arguments:
            - @accard.manager.activity
            - @accard.repository.activity
            - @accard.repository.activity_field
            - @accard.repository.activity_field_value

    accard.provider.activity:
        class: %accard.provider.activity.class%
        arguments:
            - @accard.repository.activity
            - @accard.provider.activity_prototype
