# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.accard_phase.class: Accard\Bundle\PhaseBundle\Form\Type\PhaseType
    accard.form.type.accard_phase_instance.class: Accard\Bundle\PhaseBundle\Form\Type\PhaseInstanceType

services:

    accard.form.type.accard_phase:
        class: %accard.form.type.accard_phase.class%
        tags:
            - { name: form.type, alias: accard_phase }

    accard.form.type.accard_phase_instance:
        class: %accard.form.type.accard_phase_instance.class%
        tags:
            - { name: form.type, alias: accard_phase_instance }