# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Patient\Model\Patient:
    type: mappedSuperclass
    table: accard_patient

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        mrn:
            type: string
            length: 36
            nullable: true
            unique: true
        firstName:
            type: string
            length: 36
            nullable: false
        lastName:
            type: string
            length: 36
            nullable: false
        dateOfBirth:
            type: datetime
            nullable: false
        dateOfDeath:
            type: datetime
            nullable: true
        gender:
            type: string
            nullable: true
        race:
            type: string
            nullable: true

    oneToMany:
        fields:
            targetEntity: Accard\Component\Patient\Model\FieldValueInterface
            mappedBy: subject
            cascade: ["persist", "remove"]
            orphanRemoval: true

