# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.builder.sample.class: Accard\Component\Sample\Builder\SampleBuilder
    accard.form.type.sample_source_collection.class: Accard\Bundle\SampleBundle\Form\Type\CollectionSourceType
    accard.form.type.sample_source_derivation.class: Accard\Bundle\SampleBundle\Form\Type\DerivationSourceType

services:

    accard.form.type.sample:
        class: %accard.form.type.sample.class%
        arguments:
            - %accard.model.sample.class%
            - %accard.validation_group.sample%
            - @accard.builder.sample
        tags: [{ name: form.type, alias: accard_sample }]

    accard.form.type.sample_source:
        class: %accard.form.type.sample_source.class%
        arguments:
            - %accard.model.sample_source.class%
            - %accard.validation_group.sample_source%
        tags: [{ name: form.type, alias: accard_sample_source }]

    accard.form.type.sample_source_collection:
        class: %accard.form.type.sample_source_collection.class%
        tags: [{ name: form.type, alias: accard_sample_source_collection }]

    accard.form.type.sample_source_derivation:
        class: %accard.form.type.sample_source_derivation.class%
        tags: [{ name: form.type, alias: accard_sample_source_derivation }]

    accard.builder.sample:
        class: %accard.builder.sample.class%
        arguments:
            - @accard.manager.sample
            - @accard.repository.sample
            - @accard.repository.sample_field
            - @accard.repository.sample_field_value
