# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: accard.yml }

doctrine_cache:
    providers:
        accard_settings:
            type: apc
            namespace: accard_settings

mopa_bootstrap:
    form:
        templating: AccardWebBundle::forms.html.twig
        horizontal: false
        render_optional_text: false

sensio_framework_extra:
    view:
        annotations: false

doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Accard Migrations

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

jms_serializer:
    metadata:
        auto_detection: false
        directories:
            core:
                namespace_prefix: Accard\\
                path: @AccardCoreBundle/Resources/config/serializer