# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: accard.yml }

lexik_translation:
    fallback_locale: en
    managed_locales: [en]

doctrine_cache:
    providers:
        accard_settings:
            type: apc
            namespace: accard_%accard_app_name%_settings

#mopa_bootstrap:
#    form:
#        templating: AccardWebBundle::forms.html.twig
#        horizontal: false
#        render_optional_text: false

sensio_framework_extra:
    view:
        annotations: false

doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations/%database_driver%
    namespace: Application\Migrations
    table_name: migration_versions
    name: Accard Migrations

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: html
    serializer:
        serialize_null: true

fos_elastica:
    clients:
        default: { host: %elasticsearch_host%, port: %elasticsearch_port% }
    serializer: ~
    indexes:
        accard:
            client: default
            finder: ~
            index_name: %accard_app_name%
            types:
                patient:
                    mappings:
                        firstName: { boost: 5 }
                        lastName: { boost: 5 }
                    serializer:
                        groups: [search]
                    persistence:
                        driver: orm
                        model: Accard\Component\Core\Model\Patient
                        finder: ~
                        provider: ~
                        listener:
                            insert: %elasticsearch_enabled%
                            update: %elasticsearch_enabled%
                            delete: %elasticsearch_enabled%
                            flush: %elasticsearch_enabled%
                diagnosis:
                    serializer:
                        groups: [search]
                    persistence:
                        driver: orm
                        model: Accard\Component\Core\Model\Diagnosis
                        finder: ~
                        provider: ~
                        listener:
                            insert: %elasticsearch_enabled%
                            update: %elasticsearch_enabled%
                            delete: %elasticsearch_enabled%
                            flush: %elasticsearch_enabled%
                diagnosis_code:
                    serializer:
                        groups: [search]
                    persistence:
                        driver: orm
                        model: Accard\Component\Diagnosis\Model\Code
                        finder: ~
                        provider: ~
                        listener:
                            insert: %elasticsearch_enabled%
                            update: %elasticsearch_enabled%
                            delete: %elasticsearch_enabled%
                            flush: %elasticsearch_enabled%

jms_serializer:
    metadata:
        auto_detection: false
        directories:
            core:
                namespace_prefix: Accard\Component
                path: @AccardCoreBundle/Resources/serializer
