# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Sample\Model\Sample:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        amount:
            type: integer
            nullable: false

    manyToOne:
        source:
            targetEntity: Accard\Component\Sample\Model\SourceInterface
            inversedBy: samples
            joinColumn:
                name: sourceId
                referencedColumnName: id

    oneToMany:
        derivatives:
            targetEntity: Accard\Component\Sample\Model\SourceInterface
            mappedBy: sample
        fields:
            targetEntity: Accard\Component\Sample\Model\FieldValueInterface
            mappedBy: subject
            orphanRemoval: true
            cascade: ["persist", "remove"]
