# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Sample\Model\Source:
    type: mappedSuperclass
    table: accard_sample_source

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        sourceDate:
            type: datetime
            nullable: false
        amount:
            type: integer
            nullable: true

    manyToOne:
        sample:
            targetEntity: Accard\Component\Sample\Model\SampleInterface
            inversedBy: source
            joinColumn:
                name: parentSampleId
                referencedColumnName: id

    oneToMany:
        samples:
            targetEntity: Accard\Component\Sample\Model\SampleInterface
            mappedBy: source
            cascade: ["persist", "remove"]
