# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.drug_group.class: Accard\Bundle\DrugBundle\Form\Type\DrugGroupType
    accard.form.type.drug.class: Accard\Bundle\DrugBundle\Form\Type\DrugType
    accard.form.type.drug_group_choice.class: Accard\Bundle\DrugBundle\Form\Type\DrugGroupChoiceType
    accard.form.type.drug_choice.class: Accard\Bundle\DrugBundle\Form\Type\DrugChoiceType

services:

    accard.form.type.drug_group:
        class: %accard.form.type.drug_group.class%
        arguments:
            - %accard.model.drug_group.class%
            - %accard.model.drug.class%
            - %accard.validation_group.drug_group%
        tags: [{ name: form.type, alias: accard_drug_group }]

    accard.form.type.drug:
        class: %accard.form.type.drug.class%
        arguments:
            - %accard.model.drug.class%
            - %accard.model.drug_group.class%
            - %accard.validation_group.drug%
        tags: [{ name: form.type, alias: accard_drug }]

    accard.form.type.drug_group_choice:
        class: %accard.form.type.drug_group_choice.class%
        arguments:
            - %accard.model.drug_group.class%
        tags: [{ name: form.type, alias: accard_drug_group_choice }]

    accard.form.type.drug_choice:
        class: %accard.form.type.drug_choice.class%
        arguments:
            - %accard.model.drug.class%
        tags: [{ name: form.type, alias: accard_drug_choice }]
